#include "Application.h"
#include "CommandFirewall.h"
#include "CommandParser.h"
#include "LlamaManager.h"
#include "ShellManager.h"
#include "WebSearchManager.h"
#include "imgui.h"
#include <future>

// Custom handler to prevent Ctrl+C from crashing the app
BOOL WINAPI ConsoleCtrlHandler(DWORD dwCtrlType) {
  if (dwCtrlType == CTRL_C_EVENT || dwCtrlType == CTRL_BREAK_EVENT ||
      dwCtrlType == CTRL_CLOSE_EVENT) {
    return TRUE; // Swallow the event to handle shutdown ourselves via GLFW
  }
  return FALSE;
}

std::string GetProjectRoot() {
    char path[MAX_PATH];
    GetModuleFileNameA(NULL, path, MAX_PATH);
    std::string fullPath(path);
    // Convert backslashes for consistency
    for(auto& c : fullPath) if(c == '\\') c = '/';
    
    // Look for "out/build/" string footprint generated by typical IDEs/CMake
    size_t outPos = fullPath.find("/out/build/");
    if (outPos != std::string::npos) {
        return fullPath.substr(0, outPos + 1); // Returns "path/to/AIHollowShell/"
    } 
    
    // Fallback: If not found, assume the executable is physically placed in the root directory
    size_t lastSlash = fullPath.find_last_of("/");
    if (lastSlash != std::string::npos) {
        return fullPath.substr(0, lastSlash + 1);
    }
    return "";
}

Application::Application() {
  SetConsoleCtrlHandler(ConsoleCtrlHandler, TRUE);

  m_Window = std::make_unique<Window>(WIDTH + 200, HEIGHT, "Terminal Co-Pilot");
  m_Input = std::make_unique<InputManager>(m_Window->GetWin32Handle());
  m_Gui = std::make_unique<GuiRenderer>(m_Window->GetNativeHandle());

  // Initialize Knowledge Base (RAG)
  m_KB = std::make_shared<JsonKnowledgeBase>();
  std::string dbPath = GetProjectRoot() + "tldr_database.json";
  m_KB->Load(dbPath);
  m_RAG = std::make_shared<RAGManager>(m_KB);

  // Initialize with default (Index 0 is now Qwen)
  SwitchToModel(0);

  m_IsAdmin = IsRunningAsAdmin();
}

Application::~Application() {
  // Graceful Termination
  m_StopExecution = true;
  m_IsThinking = false;

  // Wait for background tasks to complete or check termination
  if (m_ModelLoadThread.valid())
    m_ModelLoadThread.wait();
  if (m_AiThread.valid())
    m_AiThread.wait();
  if (m_ExecThread.valid())
    m_ExecThread.wait();

  SetConsoleCtrlHandler(ConsoleCtrlHandler, FALSE);
}

void Application::SwitchToModel(int index) {
  if (index < 0 || index >= (int)m_ModelFiles.size())
    return;

  m_SelectedModelIndex = index;
  m_IsLoadingModel = true;
  m_aiResponse = "Loading " + m_ModelOptions[index] + "...";

  m_ModelLoadThread = std::async(std::launch::async, [this, index]() {
    std::string modelPath = GetProjectRoot() + "models/" + m_ModelFiles[index];
    auto localAI = std::make_unique<LlamaManager>(modelPath, m_ModelOptions[index]);

    std::lock_guard<std::mutex> lock(m_ResponseMutex);
    m_AI = std::move(localAI);
    m_IsLoadingModel = false;
    m_aiResponse = m_ModelOptions[index] + " is ready.";
    m_ChatHistory.push_back({"AI", m_aiResponse, "", false, false, {}});
  });
}

bool Application::IsRunningAsAdmin() {
  BOOL fIsRunAsAdmin = FALSE;
  HANDLE hToken = NULL;
  if (OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &hToken)) {
    TOKEN_ELEVATION elevation;
    DWORD dwSize;
    if (GetTokenInformation(hToken, TokenElevation, &elevation,
                            sizeof(elevation), &dwSize)) {
      fIsRunAsAdmin = elevation.TokenIsElevated;
    }
  }
  if (hToken)
    CloseHandle(hToken);
  return fIsRunAsAdmin;
}

void Application::Run() {
  static char inputBuffer[512] = "";

  while (!m_Window->ShouldClose()) {
    if (m_Window->ProcessOSMessages(1)) {
      if (m_Window->IsVisible())
        m_Window->Hide();
      else {
        m_Window->Show();
        SetForegroundWindow(m_Window->GetWin32Handle());
      }
    }

    if (!m_Window->IsVisible()) {
      std::this_thread::sleep_for(std::chrono::milliseconds(16));
      continue;
    }

    // 2. Async Response Handling
    if (m_IsThinking && m_AiThread.valid()) {
      if (m_AiThread.wait_for(std::chrono::seconds(0)) ==
          std::future_status::ready) {
        std::string fullResponse = m_AiThread.get();
        ParsedCommand pc = CommandParser::Parse(fullResponse);

        auto finishTime = std::chrono::steady_clock::now();
        float msTime = (float)std::chrono::duration_cast<std::chrono::milliseconds>(finishTime - m_ThinkingStartTime).count();
        char timeBuf[64];
        sprintf(timeBuf, "\n\n*(Took %.0fms to respond)*", msTime);

        if (pc.success) {
          m_LastGeneratedCommand = pc.command;
          m_CommandExplanation = pc.explanation + timeBuf;
          m_CurrentSafety = ShellManager::AssessCommand(m_LastGeneratedCommand);
          m_aiResponse =
              m_CurrentSafety.isValid ? "Validated." : "Verification warning.";
        } else {
          m_aiResponse = "Analysis failed.";
          m_LastGeneratedCommand = "";
          m_CurrentSafety = {};
          pc.explanation += timeBuf; // Append even on fail
        }

        {
          std::lock_guard<std::mutex> lock(m_ResponseMutex);
          m_ChatHistory.push_back({"AI", pc.explanation, pc.command, false,
                                   pc.success, m_CurrentSafety});
        }

        m_IsThinking = false;
        m_ScrollToBottom = true;
      }
    }


    if (m_IsExecuting && m_ExecThread.valid()) {
      if (m_ExecThread.wait_for(std::chrono::seconds(0)) ==
          std::future_status::ready) {
        auto res = m_ExecThread.get();
        m_TerminalOutput = res.output;
        m_LastExitCode = res.exitCode;
        m_IsExecuting = false;
        m_ScrollToBottom = true;
      }
    }

    // 3. Render Prep
    int dw, dh;
    glfwGetFramebufferSize(m_Window->GetNativeHandle(), &dw, &dh);
    glViewport(0, 0, dw, dh);
    glClearColor(0.01f, 0.01f, 0.02f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    m_Gui->BeginFrame();

    if (ImGui::IsKeyPressed(ImGuiKey_Escape))
      m_Window->Hide();

    ImGui::SetNextWindowSize(ImVec2((float)dw, (float)dh));
    ImGui::SetNextWindowPos(ImVec2(0, 0));
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0.11f, 0.11f, 0.12f,
                                                    1.0f)); // System Dark Gray
    ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(0.2f, 0.2f, 0.22f, 1.0f));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 12.0f); // Apple Pill Style
    ImGui::PushStyleVar(ImGuiStyleVar_ChildRounding, 8.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(8, 12));

    ImGuiWindowFlags flags =
        ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
        ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar |
        ImGuiWindowFlags_NoBringToFrontOnFocus;
    ImGui::Begin("MainPanel", nullptr, flags);

    // Global Status
    bool canOperateStatus =
        !m_IsThinking && !m_IsExecuting && !m_IsLoadingModel;

    // --- TOP-LEFT: MODEL SELECTION ---
    ImGui::SetCursorPos(ImVec2(15, 10));
    ImGui::PushItemWidth(200);
    if (!canOperateStatus)
      ImGui::BeginDisabled();
    if (ImGui::BeginCombo("##ModelSelectTop",
                          m_ModelOptions[m_SelectedModelIndex].c_str())) {
      for (int i = 0; i < (int)m_ModelOptions.size(); i++) {
        if (ImGui::Selectable(m_ModelOptions[i].c_str(),
                              m_SelectedModelIndex == i))
          SwitchToModel(i);
      }
      ImGui::EndCombo();
    }
    if (!canOperateStatus)
      ImGui::EndDisabled();
    ImGui::PopItemWidth();

    if (m_IsAdmin) {
      ImGui::SameLine();
      ImGui::TextColored(ImVec4(1.0f, 0.4f, 0.4f, 0.9f), "admin");
    }

    // --- TOP LCD BAR (Global Status) ---
    {
      float time = (float)ImGui::GetTime();

      std::string statusStr;
      if (m_IsLoadingModel) {
          statusStr = "loading model...";
      } else if (m_IsThinking) {
          std::lock_guard<std::mutex> lock(m_ResponseMutex);
          statusStr = m_StatusText.empty() ? "thinking..." : m_StatusText;
          for (auto& c : statusStr) c = (char)tolower(c);
      } else {
          statusStr = "system ready";
      }

      float barWidth = 300.0f;
      float barHeight = 22.0f;
      
      ImGui::SameLine(ImGui::GetContentRegionAvail().x * 0.5f - (barWidth * 0.5f));
      
      ImVec2 startPos = ImGui::GetCursorScreenPos();
      startPos.y += 3; // Nudge down a bit to center vertically with combo boxes

      // Base Emboss (Inner Shadow)
      ImGui::GetWindowDrawList()->AddRectFilled(startPos, ImVec2(startPos.x + barWidth, startPos.y + barHeight), ImColor(0.04f, 0.04f, 0.05f, 1.0f), 4.0f);
      ImGui::GetWindowDrawList()->AddRect(startPos, ImVec2(startPos.x + barWidth, startPos.y + barHeight), ImColor(0,0,0,200), 4.0f);

      if (m_IsThinking || m_IsLoadingModel) {
          // Draw shifting color progress bar swept
          float sweepWidth = barWidth * 0.35f; 
          float sweepPos = fmodf(time * 0.6f, 1.35f) - 0.35f; 
          float barX1 = startPos.x + barWidth * sweepPos;
          float barX2 = barX1 + sweepWidth;
          if (barX1 < startPos.x) barX1 = startPos.x;
          if (barX2 > startPos.x + barWidth) barX2 = startPos.x + barWidth;
          
          if (barX1 < barX2) {
              float r = (sinf(time * 2.0f) + 1.0f) * 0.5f;
              float g = (sinf(time * 3.0f + 2.0f) + 1.0f) * 0.5f;
              float b = (sinf(time * 4.0f + 4.0f) + 1.0f) * 0.5f;
              ImColor barColor = ImColor(r * 0.7f + 0.3f, g * 0.7f + 0.3f, b * 0.7f + 0.3f, 0.6f); 
              ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(barX1, startPos.y), ImVec2(barX2, startPos.y + barHeight), barColor, 4.0f);
          }
      }

      // Add Center Text (Dynamic Stage)
      ImVec2 textSize = ImGui::CalcTextSize(statusStr.c_str());
      ImVec2 textPos = ImVec2(startPos.x + (barWidth - textSize.x) * 0.5f, startPos.y + (barHeight - textSize.y) * 0.5f);
      
      // Text Shadow for LCD depth
      ImGui::GetWindowDrawList()->AddText(ImVec2(textPos.x + 1, textPos.y + 1), ImColor(0,0,0,255), statusStr.c_str());
      if (m_IsThinking || m_IsLoadingModel) {
          ImGui::GetWindowDrawList()->AddText(textPos, ImColor(1.0f, 1.0f, 1.0f, 0.95f), statusStr.c_str());
      } else {
          ImGui::GetWindowDrawList()->AddText(textPos, ImColor(0.4f, 0.8f, 0.4f, 0.7f), statusStr.c_str());
      }

      // Output Dummy spacing so imgui knows cursor moved
      ImGui::Dummy(ImVec2(barWidth, barHeight));
    }

    // (canOperateStatus moved to top of frame)

    // RIGHT GROUP: Reset
    {
      ImGui::SameLine(ImGui::GetContentRegionAvail().x - 70);

      // Reset button
      if (!canOperateStatus)
        ImGui::BeginDisabled();
      if (ImGui::Button("Reset", ImVec2(65, 26))) {
        m_AI->ResetContext();
        m_aiResponse = "Context Cleared.";
        m_LastGeneratedCommand = "";
        m_TerminalOutput = "";
        {
          std::lock_guard<std::mutex> lock(m_ResponseMutex);
          m_ChatHistory.clear();
        }
      }
      if (!canOperateStatus)
        ImGui::EndDisabled();
    }

    ImGui::Separator();

    // --- MIDDLE SECTION ---
    float footerHeight = ImGui::GetFrameHeightWithSpacing() * 3.5f;
    float availableHeight = ImGui::GetContentRegionAvail().y - footerHeight;

    // Draggable Partition Logic
    float totalWidth = ImGui::GetContentRegionAvail().x;
    float splitHandleWidth = 10.0f;
    float minPaneWidth = 150.0f;

    float pane1Width = (totalWidth - splitHandleWidth) * m_PaneSplitRatio;
    if (pane1Width < minPaneWidth)
      pane1Width = minPaneWidth;

    float pane2Width = totalWidth - pane1Width - splitHandleWidth;
    if (pane2Width < minPaneWidth) {
      pane2Width = minPaneWidth;
      pane1Width = totalWidth - pane2Width - splitHandleWidth;
    }

    if (m_IsLoadingModel) {
      ImGui::BeginChild("LoadingPane", ImVec2(-1, availableHeight), true);
      ImGui::TextColored(ImVec4(1.0f, 0.8f, 0.0f, 1.0f),
                         "SYSTEM INITIALIZING...");
      ImGui::TextWrapped("Loading %s GGUF into memory. This may take a few "
                         "seconds depending on your hardware...",
                         m_ModelOptions[m_SelectedModelIndex].c_str());
      ImGui::EndChild();
    } else {
      // AI PANE
      float paneWidthStatus = pane1Width;
      ImGui::BeginChild("AIPane", ImVec2(paneWidthStatus, availableHeight),
                        true, 0);

      // 1. Render History
      {
        std::lock_guard<std::mutex> lock(m_ResponseMutex);
        for (const auto &msg : m_ChatHistory) {
          bool isSystemEvent =
              (msg.content.find("is ready") != std::string::npos ||
               msg.content.find("Cleared") != std::string::npos);

          if (isSystemEvent) {
            float txtWidth = ImGui::CalcTextSize(msg.content.c_str()).x;
            ImGui::SetCursorPosX((paneWidthStatus * 0.5f) - (txtWidth * 0.5f));
            ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1, 1, 1, 0.4f));
            ImGui::Text("%s", msg.content.c_str());
            ImGui::PopStyleColor();
          } else if (msg.isUser) {
            float width = ImGui::CalcTextSize(msg.content.c_str()).x;
            float maxWidth = paneWidthStatus * 0.75f;
            if (width > maxWidth)
              width = maxWidth;

            ImGui::SetCursorPosX(ImGui::GetContentRegionAvail().x - width - 15);
            ImGui::TextColored(ImVec4(0.4f, 0.6f, 1.0f, 1.0f), "User");

            ImGui::SetCursorPosX(ImGui::GetContentRegionAvail().x - width - 15);
            ImGui::PushTextWrapPos(ImGui::GetCursorPos().x + width);
            ImGui::TextWrapped("%s", msg.content.c_str());
            ImGui::PopTextWrapPos();
          } else {
            ImGui::TextColored(ImVec4(0.7f, 0.5f, 0.95f, 1.0f), "cmdAI");
            ImGui::PushTextWrapPos(ImGui::GetCursorPos().x +
                                   (paneWidthStatus - 25));
            ImGui::TextWrapped("%s", msg.content.c_str());
            ImGui::PopTextWrapPos();

            if (msg.hasCommand) {
              bool isDenied = (msg.command == "DENIED");
              bool isFirewall = (msg.command == "FIREWALL_BLOCK");

              if (!isDenied && !isFirewall) {
                ImGui::Spacing();
                ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1, 1, 1, 0.9f));
                ImGui::PushStyleColor(ImGuiCol_FrameBg,
                                      ImVec4(0.08f, 0.08f, 0.1f, 1.0f));
                ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 4.0f);

                char cmdId[32];
                sprintf(cmdId, "##cmd_hist_%p", &msg);
                ImGui::InputTextMultiline(
                    cmdId, (char *)msg.command.c_str(),
                    msg.command.length() + 1,
                    ImVec2(paneWidthStatus - 85,
                           ImGui::GetTextLineHeight() * 2.5f),
                    ImGuiInputTextFlags_ReadOnly);
                ImGui::PopStyleColor(2);
                ImGui::PopStyleVar();

                ImGui::Separator();
                ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 5);

                // --- INTEGRATED ACTION BAR ---
                static size_t s_copiedMsgId = 0;
                static double s_copyTime = 0.0;
                if (ImGui::Button(
                        (std::string("Copy##") + std::to_string((size_t)&msg))
                            .c_str(),
                        ImVec2(60, 26))) {
                  ImGui::SetClipboardText(msg.command.c_str());
                  s_copiedMsgId = (size_t)&msg;
                  s_copyTime = ImGui::GetTime();
                }
                if (ImGui::IsItemHovered()) {
                  if (s_copiedMsgId == (size_t)&msg && ImGui::GetTime() - s_copyTime < 2.0)
                    ImGui::SetTooltip("Copied!");
                  else
                    ImGui::SetTooltip("Copy command");
                }

                ImGui::SameLine();
                bool execStateAtStart = m_IsExecuting;
                if (execStateAtStart)
                  ImGui::BeginDisabled();

                ImGui::PushStyleColor(ImGuiCol_Button,
                                      ImVec4(0.12f, 0.48f, 1.0f, 1.0f));
                if (ImGui::Button(
                        (std::string("Run >##") + std::to_string((size_t)&msg))
                            .c_str(),
                        ImVec2(60, 26))) {
                  m_IsExecuting = true;
                  m_TerminalOutput = "";
                  m_LastExitCode = 0;
                  m_StopExecution = false;
                  std::string cmdToRun = msg.command;
                  m_ExecThread =
                      std::async(std::launch::async, [this, cmdToRun]() {
                        return ShellManager::Execute(
                            cmdToRun, &m_StopExecution,
                            [this](const std::string &f) {
                              std::lock_guard<std::mutex> lock(m_ResponseMutex);
                              m_TerminalOutput += f;
                              m_ScrollToBottom = true;
                            });
                      });
                }
                ImGui::PopStyleColor();

                if (ImGui::IsItemHovered())
                  ImGui::SetTooltip("Execute in terminal");
                if (execStateAtStart)
                  ImGui::EndDisabled();

                // Safety context within the block
                if (msg.safety.riskScore > 0) {
                  ImGui::SameLine();
                  ImGui::TextColored(ImVec4(1.0f, 0.5f, 0.0f, 0.9f),
                                     "Risk: %d/10", msg.safety.riskScore);
                }
              }
            }
          }
          ImGui::Separator();
        }

        if (m_ScrollToBottom) {
          ImGui::SetScrollHereY(1.0f);
          m_ScrollToBottom = false;
        }
      }

      if (m_IsThinking) {
        float time = (float)ImGui::GetTime();
        float pulse = (sinf(time * 5.0f) + 1.0f) * 0.5f;

        std::string status;
        {
            std::lock_guard<std::mutex> lock(m_ResponseMutex);
            status = m_StatusText.empty() ? "AI processing..." : m_StatusText;
        }

        // Interactive pane simplistic pulsing text
        ImGui::Spacing();
        ImGui::SetCursorPosX(25);
        
        // Scale font to be prominent but without any capsule/bar graphic
        ImGui::SetWindowFontScale(1.2f);
        ImGui::TextColored(ImVec4(0.4f, 0.7f, 1.0f, 0.6f + pulse * 0.4f), "%s", status.c_str());
        
        // Animated ellipsis
        for (int i = 0; i < 3; i++) {
          float dotOpacity = (sinf(time * 8.0f - i * 1.5f) + 1.0f) * 0.5f;
          ImGui::SameLine(0, 0);
          ImGui::TextColored(ImVec4(0.4f, 0.7f, 1.0f, dotOpacity), ".");
        }
        
        ImGui::SetWindowFontScale(1.0f); // Reset font scale for the rest of the window
        
        // Use Dummy to safely push boundaries and grow the parent scrollbar
        ImGui::Dummy(ImVec2(0, 25.0f));

        // Enforce lock to bottom while computing
        ImGui::SetScrollHereY(1.0f);
      } else if (m_ChatHistory.empty()) {
        std::lock_guard<std::mutex> lock(m_ResponseMutex);
        if (!m_aiResponse.empty()) {
          ImGui::TextWrapped("%s", m_aiResponse.c_str());
        }
      }
      ImGui::EndChild();

      // THE DRAGGABLE SPLITTER
      ImGui::SameLine();
      ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0, 0, 0, 0));
      ImGui::PushStyleColor(ImGuiCol_ButtonActive,
                            ImVec4(0.1f, 0.4f, 1.0f, 1.0f));
      ImGui::Button("##Splitter", ImVec2(splitHandleWidth, availableHeight));
      if (ImGui::IsItemActive()) {
        m_PaneSplitRatio += ImGui::GetIO().MouseDelta.x / totalWidth;
        if (m_PaneSplitRatio < 0.1f)
          m_PaneSplitRatio = 0.1f;
        if (m_PaneSplitRatio > 0.9f)
          m_PaneSplitRatio = 0.9f;
      }
      ImGui::PopStyleColor(2);
      ImGui::SameLine();

      // TERMINAL PANE
      float paneWidth2Status = pane2Width;
      ImGui::BeginGroup();
      // Fixed Header Area
      ImGui::BeginChild("ExecHeader", ImVec2(paneWidth2Status, 35), true,
                        ImGuiWindowFlags_NoScrollbar);

      // Terminal Label (Static)
      ImGui::SetCursorPos(ImVec2(10, 8));
      ImGui::TextColored(ImVec4(0.6f, 0.6f, 0.7f, 1.0f), "TERMINAL");

      // Stop Button - Centralized Pro style
      if (m_IsExecuting) {
        ImGui::SameLine((paneWidth2Status * 0.5f) - 40);
        float time = (float)ImGui::GetTime();
        float pulse = (sinf(time * 8.0f) + 1.2f) * 0.5f;
        ImVec4 stopColor = ImVec4(0.9f, 0.2f, 0.2f, 0.3f + pulse * 0.3f);
        ImGui::PushStyleColor(ImGuiCol_Button, stopColor);
        if (ImGui::Button("Stop", ImVec2(80, 24)))
          m_StopExecution = true;
        ImGui::PopStyleColor();
      }

      // Copy Button - Right Aligned
      ImGui::SameLine(paneWidth2Status - 120);
      ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1, 1, 1, 0.6f));
      static double s_outCopyTime = 0.0;
      if (ImGui::Button("Copy Output", ImVec2(100, 26))) {
        ImGui::SetClipboardText(m_TerminalOutput.c_str());
        s_outCopyTime = ImGui::GetTime();
      }
      if (ImGui::IsItemHovered()) {
        if (ImGui::GetTime() - s_outCopyTime < 2.0)
          ImGui::SetTooltip("Copied!");
      }
      ImGui::PopStyleColor();

      // Fix it Button - Only if last command failed
      if (m_LastExitCode != 0 && !m_TerminalOutput.empty() && !m_IsExecuting &&
          !m_IsThinking) {
        ImGui::SameLine(paneWidth2Status - 230);
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.8f, 0.2f, 0.2f, 0.6f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered,
                              ImVec4(0.9f, 0.3f, 0.3f, 0.8f));
        if (ImGui::Button("Fix it", ImVec2(100, 26))) {
          std::string failedCmd = m_LastGeneratedCommand;
          std::string errorOut = m_TerminalOutput;

          // 1. Retrieve the original intent from the chat history
          std::string originalIntent = "Unknown";
          {
              std::lock_guard<std::mutex> lock(m_ResponseMutex);
              for (auto it = m_ChatHistory.rbegin(); it != m_ChatHistory.rend(); ++it) {
                  if (it->isUser) {
                      originalIntent = it->content;
                      break;
                  }
              }
          }

          // 2. Fetch RAG Context for original intent
          std::string ragDocs = "";
          if (m_RAG) {
              std::string lowerIntent = originalIntent;
              for (auto &c : lowerIntent) c = (char)tolower(c);
              ragDocs = m_RAG->RetrieveContext(lowerIntent);
          }

          // 3. Construct a Chain-of-Thought style fix prompt
          std::string fixPrompt = 
              "Original Goal: " + originalIntent + "\n" +
              "Command Executed: " + failedCmd + "\n" +
              "Console Error Output:\n" + errorOut + "\n\n" +
              "TASK: Analyze the error output. Explain exactly why the command failed. "
              "Then, provide the corrected Windows PowerShell command in a markdown powershell code block:\n"
              "```powershell\n[your raw command here]\n```\n";
              
          if (!ragDocs.empty()) {
              fixPrompt += "\nCRITICAL REFERENCE:\n" + ragDocs + "\n";
          }

          // Trigger AI reasoning
          m_IsThinking = true;
          m_ThinkingStartTime = std::chrono::steady_clock::now();
          m_aiResponse = "";
          m_AiThread = std::async(std::launch::async, [this, fixPrompt, errorOut]() {
            {
               std::lock_guard<std::mutex> lock(m_ResponseMutex);
               m_StatusText = "Searching web for solutions...";
               m_ScrollToBottom = true;
            }
            
            // Clean up the error to a concise search query
            std::string firstLineError = errorOut;
            size_t newlinePos = errorOut.find('\n');
            if (newlinePos != std::string::npos) {
                firstLineError = errorOut.substr(0, newlinePos);
            }
            // Remove carriage returns if any
            firstLineError.erase(std::remove(firstLineError.begin(), firstLineError.end(), '\r'), firstLineError.end());
            
            std::string searchQuery = firstLineError + " powershell solution";
            
            // Connect to search engine dynamically using just the top-level error signature
            std::string webSnippets = WebSearchManager::SearchBrave(searchQuery);
            std::string hints = "";
            if (!webSnippets.empty()) {
                hints = "WEB SEARCH RESULTS FOR THIS ERROR:\n" + webSnippets + "\n";
            }

            auto feedback = [this](const std::string &t) {
              std::lock_guard<std::mutex> lock(m_ResponseMutex);
              m_aiResponse += t;
              m_ScrollToBottom = true;
            };

            {
               std::lock_guard<std::mutex> lock(m_ResponseMutex);
               m_StatusText = "Consulting AI model...";
               m_ScrollToBottom = true;
            }
            
            return m_AI->GenerateCommand(fixPrompt, feedback, hints, false);
          });
        }
        ImGui::PopStyleColor(2);
      }
      ImGui::EndChild();

      // Scrolling Output Area with dynamic horizontal scrolling expansion
      float headerHeight = 35.0f;
      float spacing = ImGui::GetStyle().ItemSpacing.y;
      ImGui::BeginChild("ExecContent",
                        ImVec2(0, availableHeight - headerHeight - spacing),
                        true, ImGuiWindowFlags_HorizontalScrollbar);
      {
        std::lock_guard<std::mutex> lock(m_ResponseMutex);
        std::string outTxt =
            m_TerminalOutput.empty() ? "(No output)" : m_TerminalOutput;

        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(0, 0, 0, 0));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0.9f, 0.9f, 0.9f, 1.0f));
        
        ImVec2 textSize = ImGui::CalcTextSize(outTxt.c_str());
        float inputWidth = (textSize.x > ImGui::GetWindowWidth() - 20) ? textSize.x + 30.0f : -1.0f;

        ImGui::InputTextMultiline("##term_out", (char *)outTxt.c_str(),
                                  outTxt.length() + 1, ImVec2(inputWidth, -1),
                                  ImGuiInputTextFlags_ReadOnly);
        ImGui::PopStyleColor(2);
      }
      if (m_IsExecuting)
        ImGui::TextColored(ImVec4(0.3f, 0.6f, 1.0f, 1.0f), "\n> RUNNING...");
      if (m_ScrollToBottom) {
        ImGui::SetScrollHereY(1.0f);
        m_ScrollToBottom = false;
      }
      ImGui::EndChild();
      ImGui::EndGroup();
    }

    // --- FOOTER: UNIFIED COMMAND BAR ---
    ImGui::SetCursorPosY(ImGui::GetWindowHeight() - 75);
    float barWidth = totalWidth * 0.85f;
    ImGui::SetCursorPosX((totalWidth - barWidth) * 0.5f);

    ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(0.15f, 0.15f, 0.18f, 1.0f));
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 30.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(20, 15));

    ImGui::BeginChild("CommandBar", ImVec2(barWidth, 60), true,
                      ImGuiWindowFlags_NoScrollbar |
                          ImGuiWindowFlags_NoBackground);

    if (!canOperateStatus)
      ImGui::BeginDisabled();

    ImGui::SetCursorPosY(10); // Center items vertically in the 60px child
    ImGui::SetNextItemWidth(barWidth - 110);
    ImGui::SetCursorPosX(15);
    bool executePressed = false;
    ImVec2 inputFieldPos(0, 0);
    bool inputFocused = false;
    if (ImGui::InputTextWithHint(
            "##cmd", "Ask intent (e.g. check system health, list my ip)...",
            inputBuffer, 512, ImGuiInputTextFlags_EnterReturnsTrue)) {
      executePressed = true;
    }
    inputFieldPos = ImGui::GetItemRectMin();
    inputFocused = ImGui::IsItemActive() || ImGui::IsItemFocused();

    ImGui::SameLine(barWidth - 75);
    ImGui::SetCursorPosY(10); // Match input vertical alignment
    ImGui::PushStyleColor(ImGuiCol_Button,
                          m_IsThinking ? ImVec4(0.2f, 0.2f, 0.2f, 1.0f)
                                       : ImVec4(0.12f, 0.48f, 1.0f, 1.0f));
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 22.0f);
    if (ImGui::Button("Send", ImVec2(65, 40))) {
      executePressed = true;
    }
    ImGui::PopStyleVar();
    ImGui::PopStyleColor();

    if (executePressed) {
      std::string userIn(inputBuffer);
      auto firewallRes = CommandFirewall::Assess(userIn);
      {
        std::lock_guard<std::mutex> lock(m_ResponseMutex);
        m_ChatHistory.push_back({"User", userIn, "", true, false, {}});
      }

      if (firewallRes.blocked) {
        m_aiResponse = "";
        m_LastGeneratedCommand = "FIREWALL_BLOCK";
        m_CommandExplanation = firewallRes.reason;
        {
          std::lock_guard<std::mutex> lock(m_ResponseMutex);
          m_ChatHistory.push_back(
              {"AI", firewallRes.reason, "", false, false, {}});
        }
      } else {
        m_IsThinking = true;
        m_ThinkingStartTime = std::chrono::steady_clock::now();
        m_aiResponse = "";
        m_AiThread = std::async(std::launch::async, [this, userIn]() {
          {
            std::lock_guard<std::mutex> lock(m_ResponseMutex);
            m_StatusText = "Searching system help...";
          }

          std::string hints = "";

          std::string lowerUserIn = userIn;
          for (auto &c : lowerUserIn)
            c = (char)tolower(c);

          std::string ragDocs = m_RAG->RetrieveContext(lowerUserIn);
          if (!ragDocs.empty()) {
            hints = "CRITICAL INSTRUCTION: You MUST use the following documentation to answer. Do not use your internal knowledge if it contradicts this.\n\n--- TLDR DOCUMENTATION CONTEXT ---\n" + ragDocs + "\n";
          }

          auto feedback = [this](const std::string &t) {
            std::lock_guard<std::mutex> lock(m_ResponseMutex);
            m_aiResponse += t;
            m_ScrollToBottom = true;
          };

          {
            std::lock_guard<std::mutex> lock(m_ResponseMutex);
            m_StatusText = "Consulting AI model...";
            m_ScrollToBottom = true;
          }
          std::string firstResult =
              m_AI->GenerateCommand(userIn, feedback, hints);

          // --- CHAIN OF VERIFICATION: Stage 2 (OS Check) ---
          {
            std::lock_guard<std::mutex> lock(m_ResponseMutex);
            m_StatusText = "Verifying command with Windows...";
            m_ScrollToBottom = true;
          }
          std::string verifiedCommand = firstResult;
          auto pc = CommandParser::Parse(firstResult);
          auto risk = ShellManager::AssessCommand(pc.command);

          if (!risk.isValid && pc.success) {
            {
              std::lock_guard<std::mutex> lock(m_ResponseMutex);
              m_StatusText = "Detected error. Auto-correcting...";
              m_ScrollToBottom = true;
            }
            // Stage 3: Automated Correction Pass
            std::string correctionHint =
                "SYSTEM VERIFICATION FAILED: The command '" + pc.command +
                "' is not a recognized internal or command. "
                "Provide a valid Windows utility. Do NOT output a filename.";

            {
              std::lock_guard<std::mutex> lock(m_ResponseMutex);
              m_aiResponse +=
                  "\n[System: Invalid command, self-correcting...]\n";
              m_ScrollToBottom = true;
            }

            // PIVOT: Second pass with strong corrective feedback explicitly as the new user input turn
            verifiedCommand =
                m_AI->GenerateCommand(correctionHint, feedback, "");
          }

          {
            std::lock_guard<std::mutex> lock(m_ResponseMutex);
            m_StatusText = ""; // Clear status
            m_ScrollToBottom = true;
          }
          return verifiedCommand;
        });
      }
      memset(inputBuffer, 0, 512);
    }
    if (!canOperateStatus)
      ImGui::EndDisabled();
    ImGui::EndChild();

    ImGui::PopStyleVar(2);
    ImGui::PopStyleColor();

    ImGui::PopStyleColor(2);
    ImGui::PopStyleVar(5);
    ImGui::End();
    m_Gui->EndFrame();
    m_Window->SwapBuffers();
  }
}
